title: Jon Almazán
logo: image.jpg
theme: jekyll-theme-minimal
#description: > # your text below (remove <br> elements if you don't need line breaks)
#  <br><br>
#  <a href="https://www.linkedin.com/in/jalmazan/"> <img src="https://img.shields.io/badge/LinkedIn-blue?logo=LinkedIn"> </a> 
